
import React from 'react';
import { motion } from 'framer-motion';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQSection: React.FC = () => {
  return (
    <motion.section
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.3 }}
      className="mt-12 space-y-6"
    >
      <div className="text-center space-y-2 mb-8">
        <h2 className="text-3xl md:text-4xl font-bold tracking-tight">Frequently Asked Questions</h2>
        <p className="text-muted-foreground text-lg">Everything you need to know about using Shade Tint Genie</p>
      </div>
      
      <div className="bg-card rounded-xl shadow-sm border border-border/50 p-6 md:p-8">
        <Accordion type="single" collapsible className="space-y-2">
        <AccordionItem value="what-is-color-tint">
          <AccordionTrigger className="text-left font-medium text-lg">
            What is a color tint?
          </AccordionTrigger>
          <AccordionContent className="text-muted-foreground">
            <p>
              A tint is created by adding white to a pure color, making it lighter while maintaining the original hue. 
              Tints are perfect for creating softer, more subtle color variations in your designs. They're essential 
              for creating accessible color schemes and establishing visual hierarchy.
            </p>
          </AccordionContent>
        </AccordionItem>
        
        <AccordionItem value="how-designers-use-shades">
          <AccordionTrigger className="text-left font-medium text-lg">
            How do designers use color shades?
          </AccordionTrigger>
          <AccordionContent className="text-muted-foreground">
            <p>
              Shades are created by adding black to a color, making it darker. Designers use shades to create depth, 
              contrast, and visual hierarchy in their work. They're essential for hover states, shadows, and creating 
              sophisticated color schemes that maintain brand consistency while offering functional variety.
            </p>
          </AccordionContent>
        </AccordionItem>
        
        <AccordionItem value="hex-rgb-support">
          <AccordionTrigger className="text-left font-medium text-lg">
            Can I use this tool for HEX and RGB values?
          </AccordionTrigger>
          <AccordionContent className="text-muted-foreground">
            <p>
              Yes! Our tool accepts HEX color codes and provides a visual color picker. All generated tints and shades 
              are provided in HEX format, making them perfect for web development, CSS, and design software. You can 
              easily copy any color code by clicking on it.
            </p>
          </AccordionContent>
        </AccordionItem>
        
        <AccordionItem value="copy-colors">
          <AccordionTrigger className="text-left font-medium text-lg">
            How do I copy a color?
          </AccordionTrigger>
          <AccordionContent className="text-muted-foreground">
            <p>
              Simply click on any color in the generated palette. The HEX code will be automatically copied to your 
              clipboard and you'll see a confirmation message. You can also hover over colors to see their values 
              in different formats (HEX, RGB, HSL).
            </p>
          </AccordionContent>
        </AccordionItem>
        
        <AccordionItem value="accessibility-web-design">
          <AccordionTrigger className="text-left font-medium text-lg">
            Are these colors accessible for web design?
          </AccordionTrigger>
          <AccordionContent className="text-muted-foreground">
            <p>
              Our tool generates color variations that help you create accessible designs. When using tints and shades, 
              always test contrast ratios between text and backgrounds to ensure WCAG compliance. Lighter tints work 
              well for backgrounds, while darker shades provide good contrast for text and important UI elements.
            </p>
          </AccordionContent>
        </AccordionItem>
        
        <AccordionItem value="commercial-use">
          <AccordionTrigger className="text-left font-medium text-lg">
            Can I use these colors for commercial projects?
          </AccordionTrigger>
          <AccordionContent className="text-muted-foreground">
            <p>
              Yes! All colors generated by this tool are free to use for any purpose, including commercial projects. 
              The tool itself is free and open-source. Whether you're working on websites, mobile apps, branding, 
              or print design, you can use these color variations without any restrictions.
            </p>
          </AccordionContent>
        </AccordionItem>
      </Accordion>
      </div>
    </motion.section>
  );
};

export default FAQSection;
